name: "catppuccin-frappe"

tools:

  tmux:
    clock: 219
    colors:
      dim: "$overlay2$"
      pink: "$pink$"
      selected:
        fg: "$pink$"
        bg: "$surface0$"
    powerline:
      colors:
        bg: "$surface0$"
        tint_bg0: "$overlay0$"
        tint_bg1: "$text$"
        selected: "$peach$"
        eggplant: "$pink$"
        blue: "$blue$"

  kitty:
    border_color: "#ff0000"
    prompt_color: "#00ff00"
    shared_icon: "★"
    test: "#ff00ff"

  ghostty:
    name: "Catppuccin Frappe"

  zsh:
    colors:
      red: 203
      cyan: 117
      blue: 110
      green: 149
      yellow: 179
      magenta: 176

  nvim:
    colorscheme: "catppuccin"
    theme: "frappe"
    vanilla: false
    winblend: 10
    plugin: |
      { "catppuccin/nvim", name = "catppuccin" }
    fields:
      bg: "base"
      fg: "text"
      alt_bg: "mantle"
      alt_fg: "surface2"
      comment: "overlay0"
      yellow: "yellow"
      green: "green"
      orange: "peach"
      blue: "blue"
      red: "red"
      mauve: "mauve"
      pink: "pink"
      teal: "teal"
      sky: "sky"
      accent: "pink"
      dark_bg: "crust"
      none: "NONE"
