name: "catppuccin-latte"

tools:

  tmux:
    clock: 13
    colors:
      dim: "$overlay0$"
      pink: "$pink$"
      selected:
        fg: "$pink$"
        bg: "$surface0$"
    powerline:
      colors:
        bg: "$crust$"
        tint_bg0: "$surface0$"
        tint_bg1: "$overlay2$"
        selected: "$flamingo$"
        eggplant: "$pink$"
        blue: "$sky$"

  kitty:
    border_color: "#ff0000"
    prompt_color: "#00ff00"
    shared_icon: "★"
    test: "#ff00ff"

  ghostty:
    name: "Catppuccin Latte"

  zsh:
    colors:
      red: 203
      cyan: 39
      blue: 110
      green: 149
      yellow: 179
      magenta: 176

  colorls:
    unrecognized_file: blue
    recognized_file: darkcyan
    executable_file: red
    dir: fuchsia
    dead_link: red
    link: cyan
    socket: darkgray
    blockdev: darkgray
    chardev: darkgray
    write: royalblue
    read: magenta
    exec: deeppink
    no_access: dimgray
    day_old: red
    hour_old: coral
    no_modifier: darkviolet
    file_large: red
    file_medium: coral
    file_small: darkgray
    report: darkviolet
    user: darkblue
    tree: cyan
    empty: yellow
    error: red
    normal: darkgray
    inode: violet
    addition: chartreuse
    modification: darkkhaki
    deletion: darkred
    untracked: darkorange
    unchanged: darkgreen

  nvim:
    colorscheme: "catppuccin"
    theme: "latte"
    vanilla: false
    winblend: 15
    plugin: |
      { "catppuccin/nvim", name = "catppuccin", priority = 1000 }
    fields:
      bg: "base"
      fg: "text"
      alt_bg: "mantle"
      alt_fg: "surface1"
      comment: "overlay0"
      yellow: "yellow"
      green: "green"
      orange: "peach"
      blue: "blue"
      red: "red"
      mauve: "mauve"
      pink: "pink"
      teal: "teal"
      sky: "sky"
      accent: "pink"
      dark_bg: "crust"
      none: "NONE"
