name: "onedarkpro-onedark"
polarity: "dark"

tools:

  tmux:
    clock: 170
    colors:
      dim: "$comment$"
      pink: "$purple$"
      yellow: "$yellow$"
      selected:
        fg: "$purple$"
        bg: "$cursorline$"

  fzf:
    fg: "$fg$"
    bg: "-1"
    hl: "$orange$"
    selected_bg: "$selection$"
    info: "$blue$"
    border: "$purple$"
    prompt: "$green$"
    pointer: "$red$"
    marker: "$yellow$"
    spinner: "$purple$"
    header: "$comment$"
    separator: "$gray$"
    label: "$fg$"

  ipython:
    pygments_style: "one-dark"

  ghostty:
    name: "Atom One Dark"

  kitty:

  zsh:
    colors:
      red: 204
      cyan: 38
      blue: 39
      green: 114
      yellow: 180
      magenta: 170

  colorls:
    unrecognized_file: "$blue$"
    recognized_file: "$cyan$"
    executable_file: "$green$"
    dir: "$orange$"
    dead_link: "$red$"
    link: "$cyan$"
    device: "$green$"
    write: "$blue$"
    read: "$purple$"
    exec: "$red$"
    no_access: "$comment$"
    day_old: "$purple$"
    hour_old: "$orange$"
    no_modifier: "$gray$"
    file_large: "$orange$"
    file_medium: "$yellow$"
    file_small: "$comment$"
    report: "$fg$"
    user: "$blue$"
    tree: "$gray$"
    empty: "$yellow$"
    error: "$red$"
    normal: "$white$"
    inode: "$blue$"
    addition: "$green$"
    modification: "$yellow$"
    deletion: "$red$"
    untracked: "$orange$"
    unchanged: "$cyan$"

  nvim:
    colorscheme: "onedark"
    scheme: "onedark"
    theme: "onedark"
    vanilla: true
    winblend: 0
    plugin: |
      {
        "olimorris/onedarkpro.nvim",
        priority = 1000, -- Ensure it loads first
      }
    fields:
      bg: "bg"
      fg: "fg"
      alt_bg: "bg_statusline"
      alt_fg: "gray"
      comment: "comment"
      yellow: "yellow"
      green: "green"
      orange: "orange"
      blue: "blue"
      red: "red"
      mauve: "purple"
      pink: "purple"
      teal: "cyan"
      sky: "blue"
      accent: "purple"
      dark_bg: "float_bg"
      light_bg: "selection"
      none: "NONE"
