name: "tokyonight-storm"
foreground: "#ffffff"
background: "#000000"

tools:

  tmux:
    clock: 213
    colors:
      dim: "$dark3$"
      pink: "$magenta2$"
    powerline:
      colors:
        bg: "$fg_gutter$"
        tint_bg0: "$bg_dark$"
        tint_bg1: "$fg$"
        selected: "$neon_blue$"
        eggplant: "$magenta2$"
        blue: "$blue$"

  kitty:
    name: "tokyonight_storm"
    border_color: "#ff0000"
    prompt_color: "#00ff00"
    shared_icon: "★"
    test: "#ff00ff"

  zsh:
    colors:
      red: 196
      cyan: 51
      blue: 75
      green: 40
      yellow: 214
      magenta: 198

  nvim:
    colorscheme: "tokyonight"
    theme: "storm"
    vanilla: false
    plugin: |
      {
            "folke/tokyonight.nvim",
            lazy = false,
            priority = 1000,
            opts = {},
          }
    fields:
      bg: "bg"
      fg: "fg"
      alt_bg: "bg_dark"
      alt_fg: "fg"
      comment: "comment"
      yellow: "yellow"
      green: "green"
      orange: "orange"
      blue: "blue"
      red: "red"
      mauve: "magenta"
      pink: "magenta2"
      teal: "blue1"
      sky: "blue5"
      accent: "magenta2"
