
# TPM
## List of plugins
set-option -g @plugin 'alberti42/tmux-fzf-links'
set-option -g @plugin 'embe221ed/interdimux'
set-option -g @plugin 'roosta/tmux-fuzzback'
set-option -g @plugin 'tmux-plugins/tpm'

## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
