theme: "catppuccin-latte"

font:
  family: "JetBrains Mono"
  postscript_name: "JetBrainsMono"
  features: "calt zero"
  bold: "auto"
  italic: "auto"
  bold_italic_font: "auto"
  size: 15
  symbol_font: true
  cell:
    height: "+18px"
    width: "96%"

ui:
  border: "rounded"

tmux:
  pane:
    border:
      style: "bold"
      lines: "heavy"
      format: " #{user}@#{host_short}:#{s|#(echo $HOME)|~|:pane_current_path} "
      status: "top"
  popup:
    border:
      style: "bold"

nvim:
  goto_preview:
    border: [ "├", "─" ,"╮", "│", "╯", "─", "╰", "│" ]
    title_length: 60
  lsp:
    doc:
      border: false
    diagnostic:
      border: "single"
