family: "Maple Mono"
style: "Light"
italic: "Light Italic"
# TODO: not sure if that's correct
postscript_name: "MapleMono"
symbol_font: false
kitty:
  features: "+calt +zero"
  bold: "auto"
  bold_italic: "auto"
  size: 15
  cell:
    height: "+14px"
    width: "96%"
  underline:
    position: "11px"
    thickness: "100%"
  strikethrough:
    position: "8px"
ghostty:
  features: "calt,zero"
  bold: "default"
  bold_italic: "default"
  size: 15.5
  cell:
    height: "56%"
    width: "-8%"
  underline:
    position: "14"
  padding:
    x: "4"
    y: "0"
